sources:
    include:
        - ./iOSExample/Source
        - ./iOSExampleTests
templates:
    - ../Templates
output:
    path: ./iOSExampleTests/Generated
    link:
        project: iOSExample.xcodeproj
        target: iOSExampleTests
        group: iOSExampleTests/Generated
args:
    testables:
        - iOSExample
