sources:
    include:
        - ./iOSExample/Source
        - ./iOSExampleTests
templates:
    - ../Templates
output:
    path: ./iOSExampleTests/Generated
args:
    imports:
        - UIKit
    testables:
        - iOSExample
